# Generated by Django 4.2.6 on 2024-06-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perdiqma',
            fields=[
                ('perdiqmaID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('perdiqmaname', models.CharField(max_length=100)),
                ('perdiqmaphone', models.CharField(max_length=50)),
                ('perdiqmapass', models.CharField(max_length=150)),
                ('perdiqmabureau', models.CharField(max_length=150)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Perdiqmaadmin',
            fields=[
                ('adminID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=100)),
                ('adminphone', models.CharField(max_length=50)),
                ('adminpass', models.CharField(max_length=150)),
            ],
        ),
    ]
