# Generated by Django 4.2.6 on 2024-06-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perdiqma_homepage', '0002_remove_perdiqma_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='activity_pictures/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdiqma_homepage.perdiqmaadmin')),
                ('members', models.ManyToManyField(related_name='activities', to='perdiqma_homepage.perdiqma')),
            ],
        ),
    ]
